---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  "tag:Project": QuickSpin

hostnames:
  - tag:Name

compose:
  ansible_connection: community.aws.aws_ssm
  ansible_host: instance_id
  ansible_python_interpreter: /usr/bin/python3
